### ISSUE TITLE
Whitespaces

### ISSUE THREAD

**Issue by MRodz** [arokis/bdnprint_if#6]
Die derzeitige Lösung mit Nbsp führt leider zu Problemen bei ConTeXt, weil der Text aus dem Seitenbereich läuft. Könntest du die bitte austauschen? Ich hatte das bei mir lokal einmal umgesetzt, allerdings führt ein einfaches Austauschen des Nbsp zu einem Sp dazu, dass nach rdgMarker-Elementen ein überzähliges Leerzeichen erzeugt wird.

Die Umsetzung hier wäre relativ dringend, weil Mü diese oder nächste Woche gern mit Korrekturlesen im Griesbach beginnen möchte. Könntest du dich dem als nächstes annehmen?

**Comment by arokis** [comment]
Okay, ich habe nbsp (&#xA0;) durch space (&#x20;) ersetzt. Wenn das das Problem gelöst hat, dann kannst du #6 bitte löschen.

**Comment by MRodz** [comment]
Danke! Der Text läuft nun nicht mehraus dem Seitenbereich, überzählige Leerzeichen kommen aber weiterhin bei rdgMarker[@type = 'om'/'pp(l)'] vor:

- vor und nach hi
- vor und nach ref

Die aktuelle Fahne liegt nun auch immer im Wiki, unter "TODOs Publikation Griesbach".

**Comment by arokis** [comment]
Ich weiß jetzt, wo das Problem liegt: Wir können nochsoviel whitespace-handling betreiben, wenn aber am Ende die output-serialize funktion das XML abflacht, fallen viele Whitespaces, die intentional gesetzt und im Workflow des Zwischenformats gehandled wurden, raus - ganz egal, was ich vorher für Schritte unternehme. Mein Vorschlag: Ich liefere dir im Zwischenformat anstelle von U+0020 "SPACE" irgendetwas Anderes (z.B. wieder U+00A0 "NON-BREAK SPACE" ), was du im bdn-print Workflow als erstes durch U+0020 "SPACE" ersetzen müsstest.

**Comment by MRodz** [comment]
Können wir gern so machen!

**Comment by MRodz** [comment]
Ich habe den Griesbach jetzt mal mit dem neuen Zwischenformat durchlaufen lassen. Viele Dinge klappen schon sehr gut! Allerdings gibt es ein paar Fälle, in denen zu wenige Leerzeichen gesetzt werden, z.B. zwischen zwei bibl. Soweit ich das sehe, sind das aber alle Fälle, die ich schon über PERL abgefrühstückt habe.

Soll ich dir hier eine Auflistung schreiben, damit du das übers Zwischenformat lösen kannst, oder soll ich einfach weiter PERL verwenden? Mir ist das gleich, die entsprechenden REGEX sind eh schon geschrieben.

**Comment by arokis** [comment]
Wenn du die Fälle bereits im Preprocessing zu bdnprint drin hast, dann reicht das, denke ich.

**Comment by MRodz** [comment]
Alles, was mir noch einfällt, füge ich einfach in MRodz/bdnprint_if hinzu und stelle dann einen pull request.
